### PR TITLE
release 1.0.0-beta.18

### PR DESCRIPTION
**Pull request by tzellman**

### CODE REVIEW

**Comment by fivetanley** [comment]
@RobLoach This has not actually been released.

**Comment by RobLoach** [comment]
@fivetanley Mmmm, but tagged? https://github.com/emberjs/data/tree/v1.0.0-beta.18

**Comment by fivetanley** [comment]
Yeah, we were waiting on a commit so i decided not to push to npm, bower, or rubygems. I'll do so tomorrow when it gets updated.

**Comment by RobLoach** [comment]
Tag is gone, and reverted the merge. We can revert the revert and re-tag when you're ready. Thanks for the heads up, @fivetanley .

**Pull request merged**
